//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public string req_name { get; set; }
        public string skill { get; set; }
        public Nullable<System.DateTime> start_dat { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    }
}
