//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int detid { get; set; }
        public Nullable<int> userid { get; set; }
        public string fname { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
        public string repto { get; set; }
    }
}
