//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_exercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration_form
    {
        public string first_name { get; set; }
        public Nullable<int> age { get; set; }
        public string login_name { get; set; }
        public string pass { get; set; }
        public string cpass { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<decimal> salary_expected { get; set; }
    }
}
